### PR TITLE
Documentation for `screen`

### PR DESCRIPTION
**Pull request by YumekaMengjiaLYU**

### CODE REVIEW

**Comment by mattcieslak** [comment]
It looks like the image files aren't included in this PR

**Comment by askeller** [comment]
Hey there - I made this markdown for using "screen". Let me know if it's useful
[screen.md](https://github.com/PennLINC/PennLINC.github.io/files/7890571/screen.md)
!

**Comment by YumekaMengjiaLYU** [comment]
> Hey there - I made this markdown for using "screen". Let me know if it's useful [screen.md](https://github.com/PennLINC/PennLINC.github.io/files/7890571/screen.md) !

This is very nice and I will borrow from it -- thank you Arielle!!!

**Comment by YumekaMengjiaLYU** [comment]
> It looks like the image files aren't included in this PR

I did upload them here and the image files seem to be stored by GitHub in their server -- for example, `https://user-images.githubusercontent.com/53891017/149397837-80de4b37-d93a-4b61-acec-f542193ff69c.png`. Is there a way to double-check that the images are valid before merging?

**Comment by TinasheMTapera** [comment]
@YumekaMengjiaLYU sorry this might be a bit of work, but can you please do the following:

- for any screenshots, please replace them with code blocks. This will allow people to search the actual text of the docs as opposed to pictures. You can include both the input and output in a code block


```        # code block
screen -S example         # input code

screen -ls
There is a screen on:               # output code
	30511.example	(Detached)
1 Socket in /var/folders/9z/_nnq3vld43v61783z6t8j9yh0000gp/T/.screen. 
```

- Please make sure not to use full URLs or any full usernames anywhere; you can just put `username@cubic-sattertt` anywhere you need

**Comment by YumekaMengjiaLYU** [comment]
> @YumekaMengjiaLYU sorry this might be a bit of work, but can you please do the following:
> 
>     * for any screenshots, please replace them with code blocks. This will allow people to search the actual text of the docs as opposed to pictures. You can include both the input and output in a code block
> 
> 
> ```
> screen -S example         # input code
> 
> screen -ls
> There is a screen on:               # output code
> 	30511.example	(Detached)
> 1 Socket in /var/folders/9z/_nnq3vld43v61783z6t8j9yh0000gp/T/.screen. 
> ```
> 
>     * Please make sure not to use full URLs or any full usernames anywhere; you can just put `username@cubic-sattertt` anywhere you need

Those are great points! Will do! Let me know if there is anything additional you'd like me to add.

**Comment by TinasheMTapera** [comment]
Perfect! Thanks!

**Pull request merged**
